### ISSUE TITLE
Can not reproduce the results after re-training the network for 100 epoches.

### ISSUE THREAD

**Issue by JimZAI** [deeplearning-wisc/poem#2]
Hi, thanks for your insightful work.

When i tried to reproduce the results in Table 1, by orderly running the following scripts:
1. python train_poem.py --name POEM --in-dataset CIFAR-10 --auxiliary-dataset imagenet --epochs 100 --model-arch densenet
2. python get_score.py --name POEM --in-dataset CIFAR-10 --model-arch densenet --test_epochs 100
3. python get_results.py --name POEM  --in-dataset CIFAR-10 --test_epochs 100

I obtained the following results on the six datasets (for two tries),  which are obviously below the reported ones (2.54±0.56, 99.40±0.05, 99.50±0.07).
places365_ Energy Sum at epoch 100
FPR95:                  4.10
AUROC:                  98.74
AUPR:                   98.72
LSUN_ Energy Sum at epoch 100
FPR95:                  22.56
AUROC:                  96.27
AUPR:                   96.96
LSUN_resize_ Energy Sum at epoch 100
FPR95:                  0.00
AUROC:                  100.00
AUPR:                   100.00
iSUN_ Energy Sum at epoch 100
FPR95:                  0.00
AUROC:                  100.00
AUPR:                   100.00
dtd_ Energy Sum at epoch 100
FPR95:                  0.30
AUROC:                  99.74
AUPR:                   99.86
SVHN_ Energy Sum at epoch 100
FPR95:                  2.95
AUROC:                  99.12
AUPR:                   99.28

Avg FPR95:  4.99
Avg AUROC:  0.9898
Avg AUPR:  0.9914

Is there something wrong for my tries? 
Many thinks.

**Comment by alvinmingsf** [comment]
Hi! Thanks for your interest in our work. Note that the default hyperparameters are not optimal for CIFAR-10. For each ID dataset, posterior sampling hyperparameters need to be tuned, especially the ones controlling the variances for noises and weights:  `sigma` and `sigma_n`. To reproduce the results in the paper on CIFAR-10, please download the checkpoints from `https://www.dropbox.com/home/checkpoints_POEM/CIFAR-10`. Here are the results I just ran with the script. Hope it helps!

<img width="450" alt="Screen Shot 2022-12-28 at 10 29 59 PM" src="https://user-images.githubusercontent.com/20054386/209904475-086abf11-11b4-485c-9a4a-ec6aa7dd39a3.png">

**Comment by JimZAI** [comment]
So, could you provide the tuned hyper-parameters (e.g.  sigma and sigma_n) for CIFAR-10 and CIFAR-100?

**Comment by alvinmingsf** [comment]
> So, could you provide the tuned hyper-parameters (e.g. sigma and sigma_n) for CIFAR-10 and CIFAR-100?

The hyperparamers were tuned with an extensive grid search. As the project was completed a long time ago, we decided to upload the checkpoints to the cloud and cleaned up other stuff. I'm happy to help tuning and provide the optimal ones when the computing resources are more available.

**Comment by JimZAI** [comment]
Thanks a lot.
I will try to search the optimal ones, and wait for your responce. 
In addition, this issue will be closed once i successfully reproduce the results.

**Comment by alvinmingsf** [comment]
> Thanks a lot. I will try to search the optimal ones, and wait for your responce. In addition, this issue will be closed once i successfully reproduce the results.

You are welcome. Without tuning, I just ran with default hyperparameters except setting 'conf' to 3.0 as specified in the paper. Here are the results I obtained, which closely match the reported ones. Codebase is updated. If you still cannot reproduce the results with the latest version, please let me know. I'm also happy to help with implementation issues. 

<img width="481" alt="Screen Shot 2022-12-29 at 11 04 52 AM" src="https://user-images.githubusercontent.com/20054386/209992213-5b56ffa9-2a64-43d5-a12d-1f7e89c1b254.png">

**Comment by JimZAI** [comment]
Thanks a lot, i'll try it.

**Comment by lygjwy** [comment]
any idea about the hyper-parameters (e.g. sigma and sigma_n)  for CIFAR-100 benchmark with ImageNet64 random crop dataset as auxiliary OOD training dataset? If I change the auxiliary OOD training dataset, is it necessary to tune the hyper-parameters again? Thanks.
